FROM centos:7 as builder

ADD seagull /opt/src/seagull/seagull

RUN    yum update -y \
    && yum groupinstall -y "Development Tools" \
    && yum install -y curl git glib2-devel ksh bison flex flex-devel \
    && mkdir -p /opt/src/seagull/seagull/trunk/src/external-lib-src \
    && curl -L -o /opt/src/seagull/seagull/trunk/src/external-lib-src/sctplib-1.0.15.tar.gz \
       http://www.sctp.de/download/sctplib-1.0.15.tar.gz \
    && curl -L -o /opt/src/seagull/seagull/trunk/src/external-lib-src/socketapi-2.2.8.tar.gz \
       http://www.sctp.de/download/socketapi-2.2.8.tar.gz \
    && curl -L -o /opt/src/seagull/seagull/trunk/src/external-lib-src/openssl-1.0.2e.tar.gz \
       https://www.openssl.org/source/openssl-1.0.2e.tar.gz \
    && cd /opt/src/seagull/seagull/trunk/src \
    && ksh build-ext-lib.ksh \
    && cd /opt/src/seagull/seagull/trunk/src \
    && ksh build.ksh -target all \
    && tar czf /root/bin.tgz /opt/src/seagull/seagull/trunk/src/bin/* \
    && tar czf /root/exe-env.tgz /opt/src/seagull/seagull/trunk/src/exe-env/* \
    && tar czf /root/pkg.tgz /root/exe-env.tgz /root/bin.tgz

FROM centos:7 as distro
# RUN    yum update \
#     && yum install -y ksh locales \
#     && yum upgrade -y \
#     && locale-gen en_US.UTF-8 \
#     && dpkg-reconfigure --frontend noninteractive locales \
#     && rm -rf /var/lib/apt/lists/*
COPY --from=builder /root/pkg.tgz /root/pkg.tgz
RUN    yum update -y \
    && yum install -y ksh \
    && tar xzf /root/pkg.tgz -C /root --strip-components=1 \
    && tar xzf /root/bin.tgz -C /usr/local/bin --strip-components=7 \
    && mkdir -p /opt/seagull \
    && tar xzf /root/exe-env.tgz -C /opt/seagull --strip-components=7 \
    && mkdir -p /opt/seagull/diameter-env/logs \
    && mkdir -p /opt/seagull/h248-env/logs \
    && mkdir -p /opt/seagull/http-env/logs \
    && mkdir -p /opt/seagull/msrp-env/logs \
    && mkdir -p /opt/seagull/octcap-env/logs \
    && mkdir -p /opt/seagull/radius-env/logs \
    && mkdir -p /opt/seagull/sip-env/logs \
    && mkdir -p /opt/seagull/synchro-env/logs \
    && mkdir -p /opt/seagull/xcap-env/logs \
    && rm -f /root/*.tgz
